# Generated by Django 3.1.6 on 2021-05-16 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RequestOrganizer',
            fields=[
                ('requestOrganizerID', models.AutoField(primary_key=True, serialize=False)),
                ('hospitalName', models.CharField(max_length=100)),
                ('hospitalAddress', models.CharField(max_length=100)),
                ('businessEmail', models.EmailField(max_length=100)),
                ('uuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beng.user')),
            ],
        ),
        migrations.CreateModel(
            name='RequestDonor',
            fields=[
                ('requestDonorID', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='none', max_length=10)),
                ('usssername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beng.user')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('contactNumber', models.CharField(max_length=20)),
                ('gendr', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('female', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], default='none', max_length=10)),
                ('usser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beng.user')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addess', models.CharField(max_length=100)),
                ('gnder', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='none', max_length=10)),
                ('Donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beng.user')),
            ],
        ),
    ]
