# Generated by Django 3.1.6 on 2021-04-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20, null=True)),
                ('subject', models.TextField(max_length=20, null=True)),
                ('body', models.TextField(max_length=20, null=True)),
                ('body2', models.TextField(max_length=20, null=True)),
                ('body3', models.TextField(max_length=20, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
