# Generated by Django 3.1.6 on 2021-05-16 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beng', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='Donor',
            new_name='usser',
        ),
        migrations.RenameField(
            model_name='requestdonor',
            old_name='usssername',
            new_name='usser',
        ),
        migrations.RenameField(
            model_name='requestorganizer',
            old_name='uuser',
            new_name='usser',
        ),
    ]
