# Generated by Django 3.1.6 on 2021-06-12 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beng', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodbank',
            old_name='Address',
            new_name='blood_bank_address',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='address',
            new_name='hospital_address',
        ),
    ]
