# Generated by Django 3.1.6 on 2021-04-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beng', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='body2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='body3',
        ),
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
