# Generated by Django 3.1.6 on 2021-05-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beng', '0002_auto_20210516_1655'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Login',
        ),
    ]
