# Generated by Django 3.1.6 on 2021-04-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beng', '0002_auto_20210423_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('male', 'gender'), ('female', 'gender')], default='none', max_length=10),
        ),
    ]
